<a href="https://colab.research.google.com/github/SaketharamaBana/ASIS-adaptive-screen-interaction-sysytem/blob/main/Customer_Review_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install nltk scikit-learn pandas

Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.4.0)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.3)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (2.0.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [4]:
from google.colab import files

uploaded = files.upload()

Saving redmi6.csv to redmi6 (1).csv

In [5]:
import pandas as pd
import numpy as np
import re
import nltk

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...

True

In [7]:
df = pd.read_csv("redmi6 (1).csv", encoding='latin1')

print(df.head())

                                   Review Title             Customer name  \
0  Another Midrange killer Smartphone by Xiaomi         Rishikumar Thakur
1                         vry small size mobile                   Raza ji
2  Full display not working in all application.             Vaibhav Patel
3                               Value for Money           Amazon Customer
4                       Not worth for the money  Sudhakaran Wadakkancheri

               Rating                  Date Category  \
0  4.0 out of 5 stars     on 1 October 2018  Display
1  3.0 out of 5 stars  on 15 September 2018   Others
2  3.0 out of 5 stars  on 18 September 2018   Others
3  5.0 out of 5 stars  on 28 September 2018  Display
4  2.0 out of 5 stars  on 18 September 2018   Others

                                            Comments  \
0  Another Midrange killer Smartphone by Xiaomi\n...
1                   All ok but vry small size mobile
2                                         Quite good
3  Redmi has always have been the the king of bud...
4  worst product from MI. I am a hardcore fan of ...

                        Useful
0
1  7 people found this helpful
2  7 people found this helpful
3  2 people found this helpful
4  6 people found this helpful

In [8]:
print(df.info())
print(df.shape)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 280 entries, 0 to 279
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Review Title   280 non-null    object
 1   Customer name  280 non-null    object
 2   Rating         280 non-null    object
 3   Date           280 non-null    object
 4   Category       280 non-null    object
 5   Comments       280 non-null    object
 6   Useful         110 non-null    object
dtypes: object(7)
memory usage: 15.4+ KB
None
(280, 7)

In [9]:
df = df[['Comments','Rating']]

df.dropna(inplace=True)

df.head()

/tmp/ipykernel_12075/736610252.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.dropna(inplace=True)

                                            Comments              Rating
0  Another Midrange killer Smartphone by Xiaomi\n...  4.0 out of 5 stars
1                   All ok but vry small size mobile  3.0 out of 5 stars
2                                         Quite good  3.0 out of 5 stars
3  Redmi has always have been the the king of bud...  5.0 out of 5 stars
4  worst product from MI. I am a hardcore fan of ...  2.0 out of 5 stars

In [10]:
df['Rating'] = df['Rating'].astype(str).str.extract('(\d)').astype(int)

def get_sentiment(rating):

    if rating >= 4:
        return "Positive"

    elif rating == 3:
        return "Neutral"

    else:
        return "Negative"

df['Sentiment'] = df['Rating'].apply(get_sentiment)

df[['Rating','Sentiment']].head()

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
/tmp/ipykernel_12075/2558091653.py:1: SyntaxWarning: invalid escape sequence '\d'
  df['Rating'] = df['Rating'].astype(str).str.extract('(\d)').astype(int)
/tmp/ipykernel_12075/2558091653.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Rating'] = df['Rating'].astype(str).str.extract('(\d)').astype(int)
/tmp/ipykernel_12075/2558091653.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Sentiment'] = df['Rating'].apply(get_sentiment)

   Rating Sentiment
0       4  Positive
1       3   Neutral
2       3   Neutral
3       5  Positive
4       2  Negative

In [11]:
stop_words = set(stopwords.words('english'))

lemmatizer = WordNetLemmatizer()

def preprocess(text):

    text = text.lower()

    text = re.sub(r'[^a-zA-Z\s]', '', text)

    words = text.split()

    words = [
        lemmatizer.lemmatize(word)
        for word in words
        if word not in stop_words
    ]

    return " ".join(words)

df['Clean_Text'] = df['Comments'].apply(preprocess)

df.head()

/tmp/ipykernel_12075/798167493.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Clean_Text'] = df['Comments'].apply(preprocess)

,Comments,Rating,Sentiment,Clean_Text
0,Another Midrange killer Smartphone by Xiaomi\n...,4,Positive,another midrange killer smartphone xiaomi majo...
1,All ok but vry small size mobile,3,Neutral,ok vry small size mobile
2,Quite good,3,Neutral,quite good
3,Redmi has always have been the the king of bud...,5,Positive,redmi always king budget segmentand yet anothe...
4,worst product from MI. I am a hardcore fan of ...,2,Negative,worst product mi hardcore fan mi one really di...

In [12]:
tfidf = TfidfVectorizer(max_features=5000)

X = tfidf.fit_transform(df['Clean_Text'])

y = df['Sentiment']

In [13]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

In [14]:
model = LogisticRegression(max_iter=1000)

model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [15]:
y_pred = model.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

    Negative       1.00      0.67      0.80         9
     Neutral       0.00      0.00      0.00         3
    Positive       0.88      1.00      0.94        44

    accuracy                           0.89        56
   macro avg       0.63      0.56      0.58        56
weighted avg       0.85      0.89      0.86        56

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [16]:
new_reviews = [

    "Battery backup is excellent",

    "Worst phone ever purchased",

    "Phone performance is average"

]

clean_reviews = [preprocess(r) for r in new_reviews]

new_data = tfidf.transform(clean_reviews)

predictions = model.predict(new_data)

for review, sentiment in zip(new_reviews, predictions):

    print("Review:", review)

    print("Sentiment:", sentiment)

    print("-"*40)

Review: Battery backup is excellent
Sentiment: Positive
----------------------------------------
Review: Worst phone ever purchased
Sentiment: Negative
----------------------------------------
Review: Phone performance is average
Sentiment: Positive
----------------------------------------